require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PresetsController do

  # This should return the minimal set of attributes required to create a valid
  # Preset. As you add validations to Preset, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PresetsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all presets as @presets" do
      preset = Preset.create! valid_attributes
      get :index, {}, valid_session
      assigns(:presets).should eq([preset])
    end
  end

  describe "GET show" do
    it "assigns the requested preset as @preset" do
      preset = Preset.create! valid_attributes
      get :show, {:id => preset.to_param}, valid_session
      assigns(:preset).should eq(preset)
    end
  end

  describe "GET new" do
    it "assigns a new preset as @preset" do
      get :new, {}, valid_session
      assigns(:preset).should be_a_new(Preset)
    end
  end

  describe "GET edit" do
    it "assigns the requested preset as @preset" do
      preset = Preset.create! valid_attributes
      get :edit, {:id => preset.to_param}, valid_session
      assigns(:preset).should eq(preset)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Preset" do
        expect {
          post :create, {:preset => valid_attributes}, valid_session
        }.to change(Preset, :count).by(1)
      end

      it "assigns a newly created preset as @preset" do
        post :create, {:preset => valid_attributes}, valid_session
        assigns(:preset).should be_a(Preset)
        assigns(:preset).should be_persisted
      end

      it "redirects to the created preset" do
        post :create, {:preset => valid_attributes}, valid_session
        response.should redirect_to(Preset.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved preset as @preset" do
        # Trigger the behavior that occurs when invalid params are submitted
        Preset.any_instance.stub(:save).and_return(false)
        post :create, {:preset => { "user_id" => "invalid value" }}, valid_session
        assigns(:preset).should be_a_new(Preset)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Preset.any_instance.stub(:save).and_return(false)
        post :create, {:preset => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested preset" do
        preset = Preset.create! valid_attributes
        # Assuming there are no other presets in the database, this
        # specifies that the Preset created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Preset.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => preset.to_param, :preset => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested preset as @preset" do
        preset = Preset.create! valid_attributes
        put :update, {:id => preset.to_param, :preset => valid_attributes}, valid_session
        assigns(:preset).should eq(preset)
      end

      it "redirects to the preset" do
        preset = Preset.create! valid_attributes
        put :update, {:id => preset.to_param, :preset => valid_attributes}, valid_session
        response.should redirect_to(preset)
      end
    end

    describe "with invalid params" do
      it "assigns the preset as @preset" do
        preset = Preset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Preset.any_instance.stub(:save).and_return(false)
        put :update, {:id => preset.to_param, :preset => { "user_id" => "invalid value" }}, valid_session
        assigns(:preset).should eq(preset)
      end

      it "re-renders the 'edit' template" do
        preset = Preset.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Preset.any_instance.stub(:save).and_return(false)
        put :update, {:id => preset.to_param, :preset => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested preset" do
      preset = Preset.create! valid_attributes
      expect {
        delete :destroy, {:id => preset.to_param}, valid_session
      }.to change(Preset, :count).by(-1)
    end

    it "redirects to the presets list" do
      preset = Preset.create! valid_attributes
      delete :destroy, {:id => preset.to_param}, valid_session
      response.should redirect_to(presets_url)
    end
  end

end
